---
- name: ensure we are using ppa:ondrej/php for php
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: yes
    state: present

- name: ensure php7.3 and required extensions are installed
  apt:
    name: "{{ item }}"
  loop:
  - php7.3-fpm
  - php7.3-mbstring
  - php7.3-xml
  - php7.3-zip
  - php7.3-mysql
  - php7.3-curl
  - php7.3-gd
  - php7.3-imagick

- name: ensure composer is installed
  apt:
    name: composer

- name: set max upload file sizes
  shell: sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 999M/' /etc/php/7.3/fpm/php.ini

- name: set max upload file sizes
  shell: sed -i 's/post_max_size = 8M/post_max_size = 999M/' /etc/php/7.3/fpm/php.ini
