image: php:7.2-fpm
pipelines:
  default:
  - step:
      caches:
      - composer
      script:
      - apt-get update && apt-get install -qy git curl libmcrypt-dev unzip
      - pecl install mcrypt-1.0.1
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"
      - ln -f -s .env.pipelines .env
      - ./composer.phar install --ignore-platform-reqs
      - ./vendor/bin/phpunit
  - step:
      name: Deploy to AWS
      deployment: Staging
      trigger: manual
      image: atlassian/pipelines-awscli
      script:
      - aws deploy push --application-name $APPLICATION_NAME --s3-location s3://$S3_BUCKET/$BITBUCKET_COMMIT --ignore-hidden-files
      - aws deploy create-deployment --application-name $APPLICATION_NAME --s3-location bucket=$S3_BUCKET,key=$BITBUCKET_COMMIT,bundleType=zip --deployment-group-name $DEPLOYMENT_GROUP_NAME
