---
- hosts: all
  vars:
    deploy_branch: develop
    deploy_environment: local
    deploy_hostname: kiosk-manager.test
  become: true

  pre_tasks:
  - name: import variables for priovisioning
    include_vars: "./vars-{{ deploy_environment }}.yaml"

  roles:
  - ntp-auto-update
  - nodejs
  - cache
  - database
  - php
  - webserver
  - headless-browser
  - supervisord

  post_tasks:
  - name: ensure xdebug is installed
    apt:
      name: php-xdebug

  - name: ensure sqlite extention is installed
    apt:
      name: php7.3-sqlite3

  - name: set nginx user as vagrant
    replace:
      path: /etc/nginx/nginx.conf
      regexp: 'www-data'
      replace: 'vagrant'
      backup: yes

  - name: set php-fpm user as vagrant
    replace:
      path: /etc/php/7.3/fpm/pool.d/www.conf
      regexp: 'www-data'
      replace: 'vagrant'
      backup: yes

  - name: restart services following local changes
    service:
      name: "{{ item }}"
      state: restarted
    loop:
    - nginx
    - php7.3-fpm

  - name: set up .env file
    copy:
      remote_src: yes
      src: /var/www/kiosk_manager/.env.example
      dest: /var/www/kiosk_manager/.env

  - name: set application key
    shell: php artisan key:generate
    args:
      chdir: /var/www/kiosk_manager

  - name: reset for the devlopment environment
    shell: DB_SEED_USERS_TABLE_PASSWORD=123qweasd composer dev-reset-environment
    args:
      chdir: /var/www/kiosk_manager
      creates: passport.log

  - name: ensure ffmpeg is installed
    apt:
      name: ffmpeg
